/* ===================================================
   CLOUD GUARD WEBSITE — Supabase Configuration
   Auto-generated during build from environment variables.
   DO NOT edit this file — it will be overwritten on deploy.
   Set SUPABASE_URL and SUPABASE_ANON_KEY in Vercel env vars.
   =================================================== */

const SUPABASE_URL = '__SUPABASE_URL__';
const SUPABASE_ANON_KEY = '__SUPABASE_ANON_KEY__';

// Initialize Supabase client (supabase-js v2 loaded via CDN)
const _sb = window.supabase;
const supabase = (_sb.createClient || _sb.default?.createClient || _sb)(SUPABASE_URL, SUPABASE_ANON_KEY);
